apiVersion: v2
name: rushobservability
description: Rush Observability â€” query-api + ClickHouse
version: 0.0.2
appVersion: 0.0.1
type: application

dependencies:
  - name: clickhouse
    version: "0.3.x"
    repository: https://helm.altinity.com
    condition: clickhouse.enabled

