{{- $secretName := "rushobs-clickhouse-credentials" -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/component: clickhouse
    {{- include "rush.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  user: {{ "default" | b64enc }}
  {{- if $existingSecret }}
  password: {{ index $existingSecret.data "password" }}
  {{- else }}
  password: {{ randAlphaNum 24 | b64enc }}
  {{- end }}
