apiVersion: v1
kind: Service
metadata:
  name: {{ include "rush.fullname" . }}-frontend
  labels:
    app.kubernetes.io/component: frontend
    {{- include "rush.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
