apiVersion: v1
kind: Service
metadata:
  name: {{ include "rush.fullname" . }}-web-ui
  labels:
    app.kubernetes.io/component: web-ui
    {{- include "rush.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webUi.service.type }}
  ports:
    - name: http
      port: {{ .Values.webUi.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/component: web-ui
    app.kubernetes.io/instance: {{ .Release.Name }}
